---
title: "Research"
---

My research currently focuses on both substantive and methodological interests. My substantive interests are in comparative political behavior and political economy, specifically looking at how electoral behavior is affected by economic institutions and features. I supplement this with methodological research questions focused on the ways we can improve our ability to estimate and interpret regression models with a particular emphasis on time-series, spatial, and time-series cross-sectional data and instrumental variable designs.

#### Publications

1.  Rajan, Reshikesav, and Shane P. Singh. 2025. “Toothless compulsory voting can increase turnout: Evidence from India.” Electoral Studies 96:102951. <https://doi.org/10.1016/j.electstud.2025.102951>.
    - Featured in [UGA Today](https://news.uga.edu/toothless-compulsory-voting-can-increase-voter-turnout/) and [ScienceBlog](https://scienceblog.com/unenforced-voting-laws-can-still-boost-turnout/).

#### Software

tseffects: Software to estimate dynamic (causal) inferences and dynamic interaction effects with Soren Jordan and Garrett N. Vande Kamp.

#### Works in Progress

1.  Causal Inference with Integrated Time Series using Differenced Variables with Soren Jordan and Garrett N. Vande Kamp. *Under Review.*

2.  Compulsory Voting Weakens the Impact of Economic Voting

3.  Visualizing the Dynamic Conditional Marginal Effects of Dynamic Regression Models with Multiplicative Interactions with Soren Jordan and Garrett N. Vande Kamp
